# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number',
            field=models.IntegerField(default='0271808617'),
            preserve_default=False,
        ),
    ]
